### ISSUE TITLE
OOPS! Evaluation for calidad-aire.owl

### ISSUE THREAD

**Issue by OnToologyUser** [opencitydata/medio-ambiente-calidad-aire#1]
OOPS! has encountered 10 pitfalls  and have 1 suggestions.The Pitfalls are the following:
1. "Defining inverse relationships for a symmetric one"
2. "Using recursive definition"
3. "Defining wrong equivalent classes"
4. "Missing inverse relationships"
5. "Missing annotations"
6. "Defining a relationship inverse to itself"
7. "Missing domain or range in properties"
8. "Missing equivalent classes"
9. "Creating synonyms as classes"
10. "Misusing ontology annotations"
The Suggestions are the following:
1. "The domain and range axioms are equal for each of the following object properties. Could they be symmetric or transitive?"

 Please accept the merge request to see the evaluation report in this link. Otherwise the URL won't work.
https://rawgit.com/opencitydata/medio-ambiente-calidad-aire/master/OnToology/calidad-aire.owl/evaluation/oopsEval.html

**Comment by ocorcho** [comment]
Estos pitfalls son de la SSN Ontology
