### ISSUE TITLE
Etiqueta calidad del aire

### ISSUE THREAD

**Issue by jcballesteros** [opencitydata/medio-ambiente-calidad-aire#13]
En "named individuals" la etiqueta calidad del aire aparece como "dfadfadfa", sin embargo su hipervinculo es: http://vocab.linkeddata.es/datosabiertos/def/medio-ambiente/calidad-aire/index-en.html#EjemploAirQualityProperty

**Comment by ocorcho** [comment]
Resuelto en commit 8821e41. a falta de publicar la versión modificada de la documentación online
