### ISSUE TITLE
Nuevos elementos a medir

### ISSUE THREAD

**Issue by jcballesteros** [opencitydata/medio-ambiente-calidad-aire#15]
En el Ayuntamiento de Madrid aparecen nuevos elementos a medir en Calidad del Aire.

Son los siguientes:

- Etilbenceno
- Metano
- Hidrocarburosno metánicos (hexano)

**Comment by ocorcho** [comment]
Serán incorporados en la siguiente versión del vocabulario con su enlace al tesauro correspondiente:
* Etilbenceno: http://dd.eionet.europa.eu/vocabularyconcept/aq/pollutant/431
* Metano: http://dd.eionet.europa.eu/vocabularyconcept/aq/pollutant/41
* Hidrocarburos no metánicos (hexano): http://dd.eionet.europa.eu/vocabularyconcept/aq/pollutant/443 (creo que se refiere a este, que se denomina n-hexano)

**Comment by ocorcho** [comment]
Actualizado en commit 9ad6b25

**Comment by ocorcho** [comment]
Enviado a @ralcazar-oeg para que realice la publicación online del nuevo vocabulario

**Comment by ralcazar-oeg** [comment]
Actualizado con última versión
http://vocab.linkeddata.es/datosabiertos/def/medio-ambiente/calidad-aire
